QuotationCryptocurrency/QuotationCryptocurrency.Web/Models/CryptoModel.cs
namespace QuotationCryptocurrency.Web.Models
{
    public class CryptoModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Symbol { get; set; }

        public CryptoModel()
        {
        }

        public CryptoModel(QuotationModel quotation)
        {
            Id = quotation.CryptoId;
            Name = quotation.Name;
            Symbol = quotation.Symbol;
        }
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Models/ErrorViewModel.cs
using System;

namespace QuotationCryptocurrency.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Models/IModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuotationCryptocurrency.Web.Models
{
    public interface IModel
    {
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Models/PaginationModel.cs
using QuotationCryptocurrency.Database.Models.Pagination;
using System;

namespace QuotationCryptocurrency.Web.Models
{
    public class PaginationModel
    {
        public int PageNumber { get; set; }

        public int PageSize { get; set; }

        public int TotalCount { get; set; }

        public int TotalPages => (int) Math.Ceiling(TotalCount / (double) PageSize);

        public bool HasPreviousPage => PageNumber > 1;

        public bool HasNextPage => PageNumber < TotalPages;

        public PaginationModel(PaginationData paginationData, int totalCount)
        {
            this.PageNumber = (paginationData.PageNumber < totalCount)
                ? paginationData.PageNumber 
                : totalCount;

            this.PageSize = paginationData.PageSize;
            this.TotalCount = totalCount;
        }
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Models/QuotationModel.cs
using System;

namespace QuotationCryptocurrency.Web.Models
{
    public class QuotationModel : IModel
    {
        public int Id { get; set; }
        public int CryptoId { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public double Price { get; set; }
        public double? PercentChange1H { get; set; }
        public double? PercentChange24H { get; set; }
        public double? MarketCap { get; set; }
        public DateTime LastUpdated { get; set; }

        public override bool Equals(object obj)
        {
            if (obj is QuotationModel other)
            {
                return ((Id == other.Id) && (CryptoId == other.CryptoId)  && (Name == other.Name) && (Symbol == other.Symbol) 
                    && (Symbol == other.Symbol) && (Price.Equals(other.Price)) && (Equals(PercentChange1H, other.PercentChange1H)) 
                    && (Equals(PercentChange24H, other.PercentChange24H)) && (Equals(MarketCap, other.MarketCap)) 
                    && (LastUpdated == other.LastUpdated));
            }

            return false;
        }

        public override int GetHashCode()
        {
            return (Id * CryptoId * Name.GetHashCode() * Symbol.GetHashCode() * Price.GetHashCode() * PercentChange1H.GetHashCode() 
                    * PercentChange24H.GetHashCode() * MarketCap.GetHashCode() * LastUpdated.GetHashCode());
        }
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Models/QuotationRequest.cs
using Microsoft.AspNetCore.Mvc;
using QuotationCryptocurrency.Database.Models.Filter;
using QuotationCryptocurrency.Database.Models.Sort;

namespace QuotationCryptocurrency.Web.Models
{
    public class QuotationRequest
    {
        [FromQuery]
        public int PageNumber { get; set; }

        [FromQuery]
        public QuotationSortType SortOrder { get; set; }

        [FromBody]
        public QuotationFilterData FilterData { get; set; }
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Models/QuotationViewModel.cs
using System.Collections.Generic;
using QuotationCryptocurrency.Database.Models.Filter;
using QuotationCryptocurrency.Database.Models.Sort;

namespace QuotationCryptocurrency.Web.Models
{
    public class QuotationViewModel
    {
        public IList<QuotationModel> Quotations { get; set; }

        public QuotationSortType SortModel { get; set; }

        public QuotationFilterData FilterData { get; set; }

        public PaginationModel PaginationModel { get; set; }

        public QuotationViewModel(IList<QuotationModel> quotations, QuotationSortType sortModel, QuotationFilterData filterData, PaginationModel paginationModel)
        {
            this.Quotations = quotations;
            this.SortModel = sortModel;
            this.FilterData = filterData;
            this.PaginationModel = paginationModel;
        }
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Models/QuoteModel.cs
using System;

namespace QuotationCryptocurrency.Web.Models
{
    public class QuoteModel
    {
        public int Id { get; set; }
        public int CryptoId { get; set; }
        public double Price { get; set; }
        public double? PercentChange1h { get; set; }
        public double? PercentChange24h { get; set; }
        public double? MarketCap { get; set; }
        public DateTime LastUpdated { get; set; }

        public QuoteModel()
        {
        }

        public QuoteModel(QuotationModel quotation)
        {
            CryptoId = quotation.Id;
            Price = quotation.Price;
            PercentChange1h = quotation.PercentChange1H;
            PercentChange24h = quotation.PercentChange24H;
            MarketCap = quotation.MarketCap;
            LastUpdated = quotation.LastUpdated;
        }
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Controllers/HomeController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using QuotationCryptocurrency.Web.Models;

namespace QuotationCryptocurrency.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Controllers/QuotationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using QuotationCryptocurrency.Database.Models.Filter;
using QuotationCryptocurrency.Database.Models.Pagination;
using QuotationCryptocurrency.Database.Models.Sort;
using QuotationCryptocurrency.Database.Repositories;
using QuotationCryptocurrency.Web.Services;
using QuotationCryptocurrency.Web.Models;
using System.Collections.Generic;
using System.Linq;

namespace QuotationCryptocurrency.Web.Controllers
{
    public class QuotationController : Controller
    {
        private readonly IMapper Mapper;

        private readonly IQuotationService QuotationService;

        private readonly IQuotationRepository QuotationRepository;

        public QuotationController(IQuotationService quotationService, IMapper mapper, IQuotationRepository quotationRepository)
        {
            QuotationService = quotationService;
            QuotationRepository = quotationRepository;
            Mapper = mapper;
        } 

        public IActionResult Index(int pageNumber = 1, QuotationSortType sortOrder = QuotationSortType.None, QuotationFilterData filterData = null)
        {
            var paginationData = new PaginationData(pageNumber);

            var quotations = QuotationRepository.Get(sortOrder, filterData, paginationData).ToList();
            var quotationModels = Mapper.Map<List<QuotationModel>>(quotations);

            var quotationCount = QuotationRepository.GetTotalCount(sortOrder, filterData);
            var paginationModel = new PaginationModel(paginationData, quotationCount);

            var model = new QuotationViewModel(quotationModels, sortOrder, filterData, paginationModel);

            return View("Index", model);
        }

        public IActionResult Update()
        {
            QuotationService.Update();
            return RedirectPermanent("Index");
        }
    }
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

QuotationCryptocurrency/QuotationCryptocurrency.Web/Views/Quotation/Index.cshtml
@using SortType = QuotationCryptocurrency.Database.Models.Sort.QuotationSortType;

@addTagHelper "*, QuotationCryptocurrency"
@model QuotationViewModel

@{
    var sortName = Model.SortModel == SortType.NameAsc ? SortType.NameDesc : SortType.NameAsc;
    var sortSymbol = Model.SortModel == SortType.SymbolAsc ? SortType.SymbolDesc : SortType.SymbolAsc;
    var sortPrice = Model.SortModel == SortType.PriceAsc ? SortType.PriceDesc : SortType.PriceAsc;
    var sortPercentChange1H = Model.SortModel == SortType.PercentChange1HAsc ? SortType.PercentChange1HDesc : SortType.PercentChange1HAsc;
    var sortPercentChange24H = Model.SortModel == SortType.PercentChange24HAsc ? SortType.PercentChange24HDesc : SortType.PercentChange24HAsc;
    var sortMarketCap = Model.SortModel == SortType.MarketCapAsc ? SortType.MarketCapDesc : SortType.MarketCapAsc;
    var sortLastUpdated = Model.SortModel == SortType.LastUpdatedAsc ? SortType.LastUpdatedDesc : SortType.LastUpdatedAsc;
}

<div>
    <h2>Quotation Cryptocurrency</h2>
    <hr />

    @await Html.PartialAsync("_Filter", Model)
    <br />
    <div class="text-center">
        <a class="page-link" href="@Url.Action("Update", "Quotation")">Обновить котировки</a>
    </div>
    <br />

    <table class="table table-striped">
        <tr>
            <th>
               
                <a href="@Url.Action("Index", "Quotation", new { pageNumber = Model.PaginationModel.PageNumber, sortOrder = sortName, name = Model.FilterData.Name, symbol = Model.FilterData.Symbol})">
                    Name
                </a>
            </th>
            <th>
                <a href="@Url.Action("Index", "Quotation", new { pageNumber = Model.PaginationModel.PageNumber, sortOrder = sortSymbol, name = Model.FilterData.Name, symbol = Model.FilterData.Symbol})">
                    Symbol
                </a>
            </th>
            <th>
                <a href="@Url.Action("Index", "Quotation", new { pageNumber = Model.PaginationModel.PageNumber, sortOrder = sortPrice, name = Model.FilterData.Name, symbol = Model.FilterData.Symbol})">
                    Price
                </a>
            </th>
            <th>
                <a href="@Url.Action("Index", "Quotation", new { pageNumber = Model.PaginationModel.PageNumber, sortOrder = sortPercentChange1H, name = Model.FilterData.Name, symbol = Model.FilterData.Symbol})">
                    PercentChange1h
                </a>
            </th>
            <th>
                <a href="@Url.Action("Index", "Quotation", new { pageNumber = Model.PaginationModel.PageNumber, sortOrder = sortPercentChange24H, name = Model.FilterData.Name, symbol = Model.FilterData.Symbol})">
                    PercentChange24h
                </a>
            </th>
            <th>
                <a href="@Url.Action("Index", "Quotation", new { pageNumber = Model.PaginationModel.PageNumber, sortOrder = sortMarketCap, name = Model.FilterData.Name, symbol = Model.FilterData.Symbol})">
                    MarketCap
                </a>
            </th>
            <th>
                <a href="@Url.Action("Index", "Quotation", new { pageNumber = Model.PaginationModel.PageNumber, sortOrder = sortLastUpdated, name = Model.FilterData.Name, symbol = Model.FilterData.Symbol})">
                    LastUpdated
                </a>
            </th>
        </tr>

        @foreach (QuotationModel item in Model.Quotations)
        {
            <tr>
                <td>
                    <img src="https://s2.coinmarketcap.com/static/img/coins/32x32/@{@item.Id}.png" class="logo-sprite" alt="" height="16" width="16">
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Symbol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PercentChange1H)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PercentChange24H)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MarketCap)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastUpdated)
                </td>
            </tr>
        }
    </table>

    @await Html.PartialAsync("_Pagination", Model)

</div>

QuotationCryptocurrency/QuotationCryptocurrency.Web/Views/Quotation/_Filter.cshtml
@model QuotationViewModel

@using (Html.BeginForm( "Index", "Quotation", FormMethod.Get))
{
    <input type="hidden" name ="pageNumber" value="@Model.PaginationModel.PageNumber"/>
    <input type="hidden" name ="sortOrder" value="@Model.SortModel"/>

    <div class="form-row">
        <div class="col">
            <label class="control-label">Name:&nbsp;</label>
            @Html.TextBoxFor(m => m.FilterData.Name, new { @class = "form-control" })
        </div>
        <div class="col">
            <label class="control-label">Symbol:&nbsp;</label>
            @Html.TextBoxFor(m => m.FilterData.Symbol, new { @class = "form-control" })
        </div>
        <input type="submit" value="Фильтр" class="btn btn-primary" />
    </div>
}

QuotationCryptocurrency/QuotationCryptocurrency.Web/Views/Quotation/_Pagination.cshtml
@addTagHelper "*, QuotationCryptocurrency"

@model QuotationViewModel

<div class="container">
    <div class="d-flex flex-row">
        @if (Model.PaginationModel.HasPreviousPage)
        {
            <div class="page-item">
                @{ var pageNumberPrev = Model.PaginationModel.PageNumber - 1; }
                <a class="page-link" href="@Url.Action("Index","Quotation", new { pageNumber = pageNumberPrev, sortOrder = Model.SortModel, name = Model.FilterData.Name, symbol = Model.FilterData.Symbol })">
                    Back
                </a>
            </div>
        }
      
        <page-link page-action="Index" model="Model" ></page-link>

        @if (Model.PaginationModel.HasNextPage)
        {

            <div class="page-item">
                @{ var pageNumberNext = Model.PaginationModel.PageNumber + 1; }
                <a class="page-link" href="@Url.Action("Index","Quotation", new { pageNumber = pageNumberNext, sortOrder = Model.SortModel, name = Model.FilterData.Name, symbol = Model.FilterData.Symbol })">
                    Next
                </a>
            </div>
        }
    </div>
</div>


@*<script>
    function sendPostRequest(urlAction, data) {
        var xhr = new XMLHttpRequest();
        xhr.open('POST', urlAction);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.responseType = 'json';
   

        xhr.send(data);
    };
</script>*@

QuotationCryptocurrency/QuotationCryptocurrency.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QCrypt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QCrypt</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_NavigationPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            <a href="https://github.com/CosmosIsBeautiful">
                CosmosIsBeautiful
            </a>
            &copy; 2020
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

QuotationCryptocurrency/QuotationCryptocurrency.Web/Views/Shared/_NavigationPartial.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Quotation" asp-action="Index">Quotation</a>
    </li>
</ul>